import { systemWeights } from 'react-native-typography';
export default {
  disabledOpacity: 0.5,
  roundness: 6,
  colors: {
    hsBlueFourth: 'rgb(238, 245, 255)',
    hsBlueMain: 'rgb(36, 107, 253)',
    hsBlueSecond: 'rgb(218, 232, 255)',
    hsBlueThird: 'rgb(233, 240, 255)',
    hsGreyFifth: 'rgb(217, 217, 217)',
    hsGreyFourth: 'rgb(148, 163, 184)',
    hsGreyMain: 'rgb(43, 43, 43)',
    hsGreySecond: 'rgb(85, 85, 85)',
    hsGreySixth: 'rgb(246, 246, 246)',
    hsGreyThird: 'rgb(153, 153, 153)',
    hsOrange: 'rgb(251, 148, 0)',
    hsOverlay: 'rgba(0, 0, 0, 0.4)',
    hsRed: 'rgb(247, 85, 85)',
    hsShadow: 'rgba(0, 0, 0, 0.1)',
    hsWhite: 'rgb(255, 255, 255)',
    hs_blue_fourth: 'rgb(238, 245, 255)',
    hs_blue_main: 'rgb(36, 107, 253)',
    hs_blue_second: 'rgb(218, 232, 255)',
    hs_blue_third: 'rgb(233, 240, 255)',
    hs_grey_fifth: 'rgb(217, 217, 217)',
    hs_grey_fourth: 'rgb(148, 163, 184)',
    hs_grey_main: 'rgb(43, 43, 43)',
    hs_grey_second: 'rgb(85, 85, 85)',
    hs_grey_sixth: 'rgb(246, 246, 246)',
    hs_grey_third: 'rgb(153, 153, 153)',
    hs_orange: 'rgb(251, 148, 0)',
    hs_overlay: 'rgba(0, 0, 0, 0.4)',
    hs_red: 'rgb(247, 85, 85)',
    hs_shadow: 'rgba(0, 0, 0, 0.1)',
    hs_white: 'rgb(255, 255, 255)',
  },
  typography: {
    body1: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    body2: {
      ...systemWeights.regular,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 22,
    },
    button: {
      ...systemWeights.bold,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 16,
    },
    caption: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 16,
    },
    headline1: {
      ...systemWeights.bold,
      fontSize: 60,
      letterSpacing: 0,
      lineHeight: 71,
    },
    headline2: {
      ...systemWeights.bold,
      fontSize: 48,
      letterSpacing: 0,
      lineHeight: 58,
    },
    headline3: {
      ...systemWeights.bold,
      fontSize: 34,
      letterSpacing: 0,
      lineHeight: 40,
    },
    headline4: {
      ...systemWeights.bold,
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 34,
    },
    headline5: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 0,
      lineHeight: 26,
    },
    headline6: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 24,
    },
    overline: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 2,
      lineHeight: 16,
    },
    subtitle1: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    subtitle2: {
      ...systemWeights.regular,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 22,
    },
    custom14: {
      ...systemWeights.regular,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom15: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom16: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom17: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom18: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 10,
    },
    custom19: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 18,
    },
    custom20: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 22,
    },
    custom21: {
      ...systemWeights.regular,
      fontSize: 11,
      letterSpacing: 0,
      lineHeight: 22,
    },
    custom22: {
      ...systemWeights.regular,
      fontSize: 11,
      letterSpacing: 0,
      lineHeight: 20,
    },
  },
};
